trigger:
- master

jobs:
- job: win32_x64    
  pool:
    vmImage: 'windows-latest'

  steps:
  - script: |
      git submodule update --init --recursive
    displayName: 'Checkout dependencies'

  - script: |
      mkdir buildWin32_x64
      cd buildWin32_x64
      cmake -G "Visual Studio 16 2019" -A x64 ..
    displayName: 'Generate Win32_x64 solution'
    
  - task: MSBuild@1
    inputs:
      solution: 'buildWin32_x64/BabylonNative.sln'
      maximumCpuCount: true
      configuration: 'Release'
    displayName: 'Build WIN32_x64'

  - script: |
      cd buildWin32_x64\TestApp
      Release\TestApp.exe
    displayName: 'Running testapp'